"""add phone number using autogenerage

Revision ID: d4cc6df4bfa3
Revises: 7b4416fd4c24
Create Date: 2022-06-14 18:54:54.817671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cc6df4bfa3'
down_revision = '7b4416fd4c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
